### ISSUE TITLE
Unsigned Short Segfault 

### ISSUE THREAD

**Issue by tgebhart** [luetge/flagser#10]
Hello,

I may have come across a bug, or at least an odd limitation. I've found that flagser segfaults when reading in a network with too many nodes. In particular, I've found that networks with >65,535 nodes immediately segfault on at least the 3 machines that I have used to test this. Of course, this is a special number, as it is the maximum value for an unsigned short integer. This implies to me that, perhaps, something related to node/matrix indexing is being held in this number format and needs to be allocated more bytes for representation.

To reproduce this error, I'm attaching two flagser files. One of them works fine (fine.flag), the other segfaults (segfault.flag). The fine.flag file has 65535 nodes while the segfault.flag file has 65536 nodes. I have tested this behavior across a variety of parameter values, but the default behavior of the `./flagser` command should produce this issue as well. 
[flagser_files.zip](https://github.com/luetge/flagser/files/3726244/flagser_files.zip)

**Comment by tgebhart** [comment]
My current thought is that [this line](https://github.com/luetge/flagser/blob/master/src/flagser.cpp#L46) may be producing this behavior. I'm not sure if this max dimension is a ripser constraint or a flagser constraint, however.

**Comment by tgebhart** [comment]
Okay, I've refactored so that all data types related to dimensionality are `unsigned int` instead of `unsigned short`. This seems to have resolved the problem. I have updated this on a fork: https://github.com/tgebhart/flagser. I do not know what the performance ramifications are, so I will hold off on a pull request unless @luetge determines this is desirable.

**Comment by luetge** [comment]
Hi,

Sorry for the late reply. Happy to accept a pull request, although I would like it to be opt-in instead of default (i.e. defining an alias dimension_t for either unsigned short or unsigned int, depending on what the user wants). Also, there should not be any reason to change vertex_index_t to something larger, the flag MANY_VERTICES is meant for that.

Let me know if you want to create a pull request accordingly, otherwise I am happy you found a modification that works for you!

Best,
Daniel
