### ISSUE TITLE
Python bindings for flagser

### ISSUE THREAD

**Issue by gtauzin** [luetge/flagser#7]
Hi,
Following our email discussion with @luetge, my colleague Julián Burella at @reds-heig has written a python binding for `flagser` using `pybind11` (after careful consideration and performance benchmark of the different options). 

However, the C++ code had to be slightly modified to store in memory outputs instead of dumping them to files. We would like to make a pull request that includes the extra data structures as well as the setter/getter method required to interface with them. Those changes come within a #ifdef so that performances for your C++ users would not be impacted.

Once the modifications of the `flagser` C++ code are integrated, we plan to create a `flagser.py` repository (like there is a `ripser.py` repository). We will take care of maintaining it and having the `flagser` python library on conda-forge and building wheels for all major architecture/OS so that it can be available on PyPi.

I am opening this issue to discuss those changes and their integration to `flagser`.
Guillaume

**Comment by reds-heig** [comment]
Hi,
To give you more details about I have done so far, our objective is to retrieve the persistence diagram. In order to achieve this, I modified the `persistence_computer_t` class.
I added a `vector<vector<pair>>` attribute which is updated in `compute_zeroth_persistence` and `compute_pairs`.

We don't use them at the moment but it also possible to retrieve:

* Euler characteristic (index_t)
* betti numbers (vector<size_t>)
* cell count (vector<size_t>)

And also in order to retrieve the computed diagrams, compute_homology was updated. Instead of returning `void`, it now returns a `vector<persistence_computer_t>`. This version work also when using `KEEP_FLAG_COMPLEX_IN_MEMORY`. I wanted to know if so far, this seems good for you.

Finally, to keep the same philosophy of the library, a `#define` could enable/disable this option in order to not impact users who are not interested in this functionality. The "problem" is wants could be a relevant name for the define ?

* RETRIEVE_PERSISTENCE
* ALLOW_PYTHON_BINDINGS
* Etc.. (if you have something better, feel free to suggest it)

If you have any other suggestions/remarks, let's discuss it.
Julián

**Comment by luetge** [comment]
Hi,

Thanks for writing up the python bindings! The suggested changes sound good to me, a clear name for the feature toggle from my perspective is RECORD_PERSISTENCE, but RETRIEVE_PERSISTENCE is also good.

Feel free to send the pull request (unless there is more things to discuss), I will try my best to review it as fast as possible.

Cheers,
Daniel

**Comment by reds-heig** [comment]
Hi,

I made the PR #9.

You can edit it directly or let me know if you want me to make some changes

Cheers,
Julián

**Comment by luetge** [comment]
Hi,

I merged the pull request, thanks for contributing! How about the python binding themselves, how do you want to proceed with them?

Cheers,
Daniel

**Comment by gtauzin** [comment]
Hi, thank you very much!

We will set up a github repository and add your repository as a git submodule. Around that we will add the pybind11 bindings. We will set everything up so that it can be installed with pip and write a few unit tests to check if the compatibility with the C++ flagser has been compromised. I will take care of this in the week to come. Once this is done I will post the repos address here so you can check whether everything is OK for you.

Then, we will build pip wheels and upload the package on both PyPi and conda-forge so that is is easily available on all architectures/OS. That will take a little bit more time.

Let me know what you think!

Cheers,
Guillaume
